Adds C compiler support
wpilibsuite/wpiutil pull request #37
Opened 2017-09-19 04:47 UTC by ThadHouse

Requires 1.2.15 of plugin as well.

2017-09-19 04:50 UTC, calcmogul commented on config.gradle
> +def maCCompilerArgs =  ['-std=c++11', '-Wall', '-Wextra', '-Werror', '-pedantic-errors', '-fPIC', '-g',
Missing a lowercase c?

2017-09-19 04:52 UTC, ThadHouse commented
Fixed

2017-09-19 07:05 UTC, PeterJohnson commented on config.gradle
>                  compilerArgs << linux32BitArg
This is inconsistent ordering compared to the other groups (which put this line immediately after the `compilerArgs` line).

2017-09-19 07:05 UTC, PeterJohnson commented on config.gradle
> +def macCCompilerArgs = []
I would think the default of these should be similar to the CompilerArgs except for the `'-std=c++11'` part.

2017-11-11 08:11 UTC, ThadHouse commented
Fixed the issues. This is now good to go.

2017-11-11 20:57 UTC, calcmogul requested changes

2017-11-11 20:57 UTC, calcmogul commented on config.gradle
> +                         '-Wno-unused-parameter', '-fPIC', '-rdynamic', '-Wno-error=deprecated-declarations', '-pthread']
We don't need `-Wno-error=deprecated-declarations` anymore.

2018-04-30 07:08 UTC, closed without merging